### ISSUE TITLE
Prepending of "Level" to every subtopic, redundantly (or in some cases incongruently)

### ISSUE THREAD

**Issue by jamalex** [learningequality/sushi-chef-digitallibrary#1]
![image](https://user-images.githubusercontent.com/618416/50718239-6763f200-1042-11e9-9977-1fd73f6395e3.png)

**Comment by ivanistheone** [comment]
fixed in https://github.com/learningequality/sushi-chef-digitallibrary/commit/d5f38fd1943d02e92efcbfbf90b4d20f7bf7d13a
